import Head from 'next/head'
import Header from '@/components/header'
import MainContent from '@/components/content'

export default function Home() {
  return (
    <>
      <Head>
        <title>Cryto Search</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <main>
  <Header />
  <MainContent />
      </main>
    </>
  )
}
